import {
  BadRequestException,
  Injectable,
  NotFoundException,
  UnauthorizedException,
} from '@nestjs/common';
import { JwtService } from '@nestjs/jwt';
import { Prisma } from '@speedora/database';
import {
  generateRegistrationOptions,
  verifyRegistrationResponse,
  type AuthenticatorTransportFuture,
  type PublicKeyCredentialCreationOptionsJSON,
  type RegistrationResponseJSON,
} from '@simplewebauthn/server';
import { PrismaService } from '../../prisma/prisma.service';

// Tahap 3 Sprint 1 (Passkey Foundation) - short-lived, purpose-scoped JWT
// carrying the registration ceremony's own random challenge, same pattern
// as AuthService's MFA challenge token / OAuthController's `state` nonce
// (see that file's own comment on why this codebase uses a signed JWT
// rather than server-side session/Redis state for ephemeral auth-ceremony
// data). The challenge itself is generated by @simplewebauthn/server's
// generateRegistrationOptions(), not by us - we just need somewhere
// tamper-proof to hold it between "send options to the browser" and
// "verify what the browser sends back," without a DB row or Redis key.
const PASSKEY_REGISTRATION_PURPOSE = 'passkey_registration';
const PASSKEY_CHALLENGE_TOKEN_TTL = '5m';

export interface PasskeySummary {
  id: string;
  name: string;
  deviceType: string;
  backedUp: boolean;
  createdAt: Date;
  lastUsedAt: Date;
}

interface PasskeyRow {
  id: string;
  name: string;
  deviceType: string;
  backedUp: boolean;
  createdAt: Date;
  lastUsedAt: Date;
}

function toSummary(passkey: PasskeyRow): PasskeySummary {
  const { id, name, deviceType, backedUp, createdAt, lastUsedAt } = passkey;
  return { id, name, deviceType, backedUp, createdAt, lastUsedAt };
}

// rpID must be a valid domain with no scheme/port (WebAuthn spec) - derived
// from WEB_ORIGIN (the origin the actual navigator.credentials ceremony
// runs on in the browser, NOT this API's own origin - see this module's
// header comment) rather than duplicating a second env var by default.
// expectedOrigin for verification is WEB_ORIGIN itself, scheme+port
// included. Overridable via WEBAUTHN_RP_ID/WEBAUTHN_RP_NAME for deployments
// where the public-facing domain differs from WEB_ORIGIN (e.g. a CDN in
// front of the Next.js app).
function rpConfig(): { rpID: string; rpName: string; origin: string } {
  const webOrigin = process.env.WEB_ORIGIN ?? 'http://localhost:3000';
  const rpID = process.env.WEBAUTHN_RP_ID ?? new URL(webOrigin).hostname;
  const rpName = process.env.WEBAUTHN_RP_NAME ?? 'Speedora';
  return { rpID, rpName, origin: webOrigin };
}

// Tahap 3 Sprint 1 (Passkey Foundation) - WebAuthn credential primitives,
// split out of AuthService the same way MfaService was (a genuinely
// separate concern from AuthService's core session/credential logic, see
// that file's own comment). Uses @simplewebauthn/server (the de facto
// standard WebAuthn library - Passport/Auth0/Vercel all build on it)
// instead of hand-rolled CBOR/COSE/attestation parsing, per this
// initiative's own "use an industry-standard library, don't reinvent
// cryptography" instruction.
//
// This sprint is enrollment-only: register/list/rename/delete a passkey for
// an ALREADY-AUTHENTICATED user. There is no login-with-passkey path yet
// (that's Sprint 2) - nothing here touches AuthService.createSession() or
// the login/AuthGate flow at all.
@Injectable()
export class PasskeyService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly jwtService: JwtService,
  ) {}

  // excludeCredentials lists the user's EXISTING passkeys so the
  // authenticator prompt refuses to re-register one already on this
  // account (browser-level dedup, per the WebAuthn spec's own mechanism for
  // this - not something we'd otherwise catch until the unique-constraint
  // insert below). authenticatorSelection.residentKey: 'preferred' is a
  // deliberate product decision (not just a library default) - see this
  // initiative's Sprint 1 planning: platform authenticators (Touch ID/
  // Windows Hello/synced passkeys) get a discoverable credential, enabling
  // Sprint 2's usernameless login later, while older security keys with
  // limited resident-credential slots aren't rejected.
  async generateRegistrationOptionsFor(
    userId: string,
    userEmail: string,
  ): Promise<{ options: PublicKeyCredentialCreationOptionsJSON; challengeToken: string }> {
    const { rpID, rpName } = rpConfig();
    const existing = await this.prisma.passkey.findMany({
      where: { userId },
      select: { credentialId: true, transports: true },
    });

    const options = await generateRegistrationOptions({
      rpName,
      rpID,
      userName: userEmail,
      attestationType: 'none',
      excludeCredentials: existing.map((passkey) => ({
        id: passkey.credentialId,
        transports: passkey.transports as AuthenticatorTransportFuture[],
      })),
      authenticatorSelection: {
        residentKey: 'preferred',
        userVerification: 'preferred',
      },
    });

    const challengeToken = this.jwtService.sign(
      { sub: userId, purpose: PASSKEY_REGISTRATION_PURPOSE, challenge: options.challenge },
      { expiresIn: PASSKEY_CHALLENGE_TOKEN_TTL },
    );

    return { options, challengeToken };
  }

  // Same generic-failure posture as AuthService.verifyMfaChallengeToken -
  // "expired," "tampered," "wrong purpose," and "issued to a different
  // account" (a stolen/replayed token from another session) all collapse to
  // one message; the caller only needs to know the ceremony can't proceed.
  private verifyChallengeToken(token: string, expectedUserId: string): string {
    let payload: { sub?: string; purpose?: string; challenge?: string };
    try {
      payload = this.jwtService.verify(token);
    } catch {
      throw new UnauthorizedException('Passkey registration challenge is invalid or has expired');
    }
    if (
      payload.purpose !== PASSKEY_REGISTRATION_PURPOSE ||
      !payload.sub ||
      !payload.challenge ||
      payload.sub !== expectedUserId
    ) {
      throw new UnauthorizedException('Passkey registration challenge is invalid or has expired');
    }
    return payload.challenge;
  }

  async verifyAndSaveRegistration(
    userId: string,
    response: RegistrationResponseJSON,
    challengeToken: string,
    name: string,
  ): Promise<PasskeySummary> {
    const expectedChallenge = this.verifyChallengeToken(challengeToken, userId);
    const { rpID, origin } = rpConfig();

    let verification: Awaited<ReturnType<typeof verifyRegistrationResponse>>;
    try {
      verification = await verifyRegistrationResponse({
        response,
        expectedChallenge,
        expectedOrigin: origin,
        expectedRPID: rpID,
        // @simplewebauthn/server defaults this to true, which would reject
        // a registration from any authenticator that only asserts user
        // PRESENCE (a bare security key with no PIN/biometric) - that
        // contradicts generateRegistrationOptionsFor's own
        // authenticatorSelection.userVerification: 'preferred' above, which
        // deliberately keeps those authenticators eligible. Whether a given
        // LOGIN's assertion carried real user verification is judged at
        // Sprint 2's authentication time (per this initiative's own
        // "UV passkey = MFA-equivalent" decision), not baked in here as a
        // registration-time requirement.
        requireUserVerification: false,
      });
    } catch {
      // @simplewebauthn/server throws on a malformed/tampered response
      // rather than returning verified: false - collapse both into the
      // same client error, same posture as MfaService.verifyTotpCode's own
      // try/catch around otplib.
      throw new BadRequestException('Could not verify passkey registration');
    }

    if (!verification.verified || !verification.registrationInfo) {
      throw new BadRequestException('Could not verify passkey registration');
    }

    const { credential, credentialDeviceType, credentialBackedUp } = verification.registrationInfo;
    const trimmedName = name.trim() || 'Passkey';

    try {
      const passkey = await this.prisma.passkey.create({
        data: {
          userId,
          credentialId: credential.id,
          publicKey: Buffer.from(credential.publicKey),
          counter: BigInt(credential.counter),
          deviceType: credentialDeviceType,
          backedUp: credentialBackedUp,
          transports: credential.transports ?? [],
          name: trimmedName,
        },
      });
      return toSummary(passkey);
    } catch (error) {
      // P2002 = unique constraint on credentialId - this exact authenticator
      // credential is already registered (excludeCredentials above should
      // normally prevent this at the browser level, but a credential
      // registered to a DIFFERENT account isn't in this account's
      // excludeCredentials list, so the DB constraint is the real backstop).
      if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === 'P2002') {
        throw new BadRequestException('This passkey is already registered');
      }
      throw error;
    }
  }

  async list(userId: string): Promise<PasskeySummary[]> {
    const passkeys = await this.prisma.passkey.findMany({
      where: { userId },
      orderBy: { createdAt: 'asc' },
    });
    return passkeys.map(toSummary);
  }

  async rename(userId: string, id: string, name: string): Promise<PasskeySummary> {
    const trimmedName = name.trim();
    if (!trimmedName) {
      throw new BadRequestException('Name cannot be empty');
    }
    const { count } = await this.prisma.passkey.updateMany({
      where: { id, userId },
      data: { name: trimmedName },
    });
    if (count === 0) {
      throw new NotFoundException(`Passkey ${id} not found`);
    }
    const passkey = await this.prisma.passkey.findUniqueOrThrow({ where: { id } });
    return toSummary(passkey);
  }

  // Hard delete, same deleteMany-by-userId+id pattern as
  // AuthService.unlinkOAuthProvider (see Passkey model's own comment on why
  // this is a hard delete rather than TrustedDevice's soft revokedAt).
  // Deliberately NOT gated by an "at least one sign-in method must remain"
  // check the way unlinkOAuthProvider is - passkeys aren't a login method
  // yet in Sprint 1 (see this file's header comment), so deleting every
  // passkey a user has cannot lock them out of anything today. Sprint 2
  // must revisit this once passkey login exists.
  async delete(userId: string, id: string): Promise<void> {
    const { count } = await this.prisma.passkey.deleteMany({ where: { id, userId } });
    if (count === 0) {
      throw new NotFoundException(`Passkey ${id} not found`);
    }
  }
}
