import {
  BadRequestException,
  Injectable,
  NotFoundException,
  UnauthorizedException,
} from '@nestjs/common';
import { JwtService } from '@nestjs/jwt';
import { Prisma } from '@speedora/database';
import {
  generateAuthenticationOptions,
  generateRegistrationOptions,
  verifyAuthenticationResponse,
  verifyRegistrationResponse,
  type AuthenticationResponseJSON,
  type AuthenticatorTransportFuture,
  type PublicKeyCredentialCreationOptionsJSON,
  type PublicKeyCredentialRequestOptionsJSON,
  type RegistrationResponseJSON,
} from '@simplewebauthn/server';
import { PrismaService } from '../../prisma/prisma.service';

// Tahap 3 Sprint 1/2 (Passkey Foundation/Login) - short-lived, purpose-
// scoped JWTs carrying a ceremony's own random challenge, same pattern as
// AuthService's MFA challenge token / OAuthController's `state` nonce (see
// that file's own comment on why this codebase uses a signed JWT rather
// than server-side session/Redis state for ephemeral auth-ceremony data).
// The challenge itself is generated by @simplewebauthn/server's own
// generateRegistrationOptions()/generateAuthenticationOptions(), not by us -
// we just need somewhere tamper-proof to hold it between "send options to
// the browser" and "verify what the browser sends back," without a DB row
// or Redis key. Registration's token carries a `sub` (the already-
// authenticated caller); login's does not - nobody's identity is known
// until the assertion itself resolves it, same "no `sub`, just a nonce"
// shape as OAuthController's login-flow `state`.
const PASSKEY_REGISTRATION_PURPOSE = 'passkey_registration';
const PASSKEY_LOGIN_PURPOSE = 'passkey_login';
const PASSKEY_CHALLENGE_TOKEN_TTL = '5m';

export interface PasskeySummary {
  id: string;
  name: string;
  deviceType: string;
  backedUp: boolean;
  createdAt: Date;
  lastUsedAt: Date;
}

interface PasskeyRow {
  id: string;
  name: string;
  deviceType: string;
  backedUp: boolean;
  createdAt: Date;
  lastUsedAt: Date;
}

function toSummary(passkey: PasskeyRow): PasskeySummary {
  const { id, name, deviceType, backedUp, createdAt, lastUsedAt } = passkey;
  return { id, name, deviceType, backedUp, createdAt, lastUsedAt };
}

// rpID must be a valid domain with no scheme/port (WebAuthn spec) - derived
// from WEB_ORIGIN (the origin the actual navigator.credentials ceremony
// runs on in the browser, NOT this API's own origin - see this module's
// header comment) rather than duplicating a second env var by default.
// expectedOrigin for verification is WEB_ORIGIN itself, scheme+port
// included. Overridable via WEBAUTHN_RP_ID/WEBAUTHN_RP_NAME for deployments
// where the public-facing domain differs from WEB_ORIGIN (e.g. a CDN in
// front of the Next.js app).
function rpConfig(): { rpID: string; rpName: string; origin: string } {
  const webOrigin = process.env.WEB_ORIGIN ?? 'http://localhost:3000';
  const rpID = process.env.WEBAUTHN_RP_ID ?? new URL(webOrigin).hostname;
  const rpName = process.env.WEBAUTHN_RP_NAME ?? 'Speedora';
  return { rpID, rpName, origin: webOrigin };
}

// Tahap 3 Sprint 1/2 (Passkey Foundation/Login) - WebAuthn credential
// primitives, split out of AuthService the same way MfaService was (a
// genuinely separate concern from AuthService's core session/credential
// logic, see that file's own comment). Uses @simplewebauthn/server (the de
// facto standard WebAuthn library - Passport/Auth0/Vercel all build on it)
// instead of hand-rolled CBOR/COSE/attestation parsing, per this
// initiative's own "use an industry-standard library, don't reinvent
// cryptography" instruction.
//
// Sprint 1 covers enrollment (register/list/rename/delete a passkey for an
// ALREADY-AUTHENTICATED user). Sprint 2 adds login (generateAuthentication-
// OptionsFor/verifyAuthentication below) - deliberately usernameless/
// discoverable-credential based (no allowCredentials restriction), matching
// Sprint 1's residentKey: 'preferred' registration choice. This service
// itself never calls AuthService.createSession() - PasskeyController's
// login/verify route does that, reusing the exact same risk/trusted-device/
// MFA-challenge branch AuthController.login already runs, so there is only
// ever one place that decides "does this login get a session."
@Injectable()
export class PasskeyService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly jwtService: JwtService,
  ) {}

  // excludeCredentials lists the user's EXISTING passkeys so the
  // authenticator prompt refuses to re-register one already on this
  // account (browser-level dedup, per the WebAuthn spec's own mechanism for
  // this - not something we'd otherwise catch until the unique-constraint
  // insert below). authenticatorSelection.residentKey: 'preferred' is a
  // deliberate product decision (not just a library default) - see this
  // initiative's Sprint 1 planning: platform authenticators (Touch ID/
  // Windows Hello/synced passkeys) get a discoverable credential, enabling
  // Sprint 2's usernameless login later, while older security keys with
  // limited resident-credential slots aren't rejected.
  async generateRegistrationOptionsFor(
    userId: string,
    userEmail: string,
  ): Promise<{ options: PublicKeyCredentialCreationOptionsJSON; challengeToken: string }> {
    const { rpID, rpName } = rpConfig();
    const existing = await this.prisma.passkey.findMany({
      where: { userId },
      select: { credentialId: true, transports: true },
    });

    const options = await generateRegistrationOptions({
      rpName,
      rpID,
      userName: userEmail,
      attestationType: 'none',
      excludeCredentials: existing.map((passkey) => ({
        id: passkey.credentialId,
        transports: passkey.transports as AuthenticatorTransportFuture[],
      })),
      authenticatorSelection: {
        residentKey: 'preferred',
        userVerification: 'preferred',
      },
    });

    const challengeToken = this.jwtService.sign(
      { sub: userId, purpose: PASSKEY_REGISTRATION_PURPOSE, challenge: options.challenge },
      { expiresIn: PASSKEY_CHALLENGE_TOKEN_TTL },
    );

    return { options, challengeToken };
  }

  // Same generic-failure posture as AuthService.verifyMfaChallengeToken -
  // "expired," "tampered," "wrong purpose," and "issued to a different
  // account" (a stolen/replayed token from another session) all collapse to
  // one message; the caller only needs to know the ceremony can't proceed.
  private verifyChallengeToken(token: string, expectedUserId: string): string {
    let payload: { sub?: string; purpose?: string; challenge?: string };
    try {
      payload = this.jwtService.verify(token);
    } catch {
      throw new UnauthorizedException('Passkey registration challenge is invalid or has expired');
    }
    if (
      payload.purpose !== PASSKEY_REGISTRATION_PURPOSE ||
      !payload.sub ||
      !payload.challenge ||
      payload.sub !== expectedUserId
    ) {
      throw new UnauthorizedException('Passkey registration challenge is invalid or has expired');
    }
    return payload.challenge;
  }

  async verifyAndSaveRegistration(
    userId: string,
    response: RegistrationResponseJSON,
    challengeToken: string,
    name: string,
  ): Promise<PasskeySummary> {
    const expectedChallenge = this.verifyChallengeToken(challengeToken, userId);
    const { rpID, origin } = rpConfig();

    let verification: Awaited<ReturnType<typeof verifyRegistrationResponse>>;
    try {
      verification = await verifyRegistrationResponse({
        response,
        expectedChallenge,
        expectedOrigin: origin,
        expectedRPID: rpID,
        // @simplewebauthn/server defaults this to true, which would reject
        // a registration from any authenticator that only asserts user
        // PRESENCE (a bare security key with no PIN/biometric) - that
        // contradicts generateRegistrationOptionsFor's own
        // authenticatorSelection.userVerification: 'preferred' above, which
        // deliberately keeps those authenticators eligible. Whether a given
        // LOGIN's assertion carried real user verification is judged at
        // Sprint 2's authentication time (per this initiative's own
        // "UV passkey = MFA-equivalent" decision), not baked in here as a
        // registration-time requirement.
        requireUserVerification: false,
      });
    } catch {
      // @simplewebauthn/server throws on a malformed/tampered response
      // rather than returning verified: false - collapse both into the
      // same client error, same posture as MfaService.verifyTotpCode's own
      // try/catch around otplib.
      throw new BadRequestException('Could not verify passkey registration');
    }

    if (!verification.verified || !verification.registrationInfo) {
      throw new BadRequestException('Could not verify passkey registration');
    }

    const { credential, credentialDeviceType, credentialBackedUp } = verification.registrationInfo;
    const trimmedName = name.trim() || 'Passkey';

    try {
      const passkey = await this.prisma.passkey.create({
        data: {
          userId,
          credentialId: credential.id,
          publicKey: Buffer.from(credential.publicKey),
          counter: BigInt(credential.counter),
          deviceType: credentialDeviceType,
          backedUp: credentialBackedUp,
          transports: credential.transports ?? [],
          name: trimmedName,
        },
      });
      return toSummary(passkey);
    } catch (error) {
      // P2002 = unique constraint on credentialId - this exact authenticator
      // credential is already registered (excludeCredentials above should
      // normally prevent this at the browser level, but a credential
      // registered to a DIFFERENT account isn't in this account's
      // excludeCredentials list, so the DB constraint is the real backstop).
      if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === 'P2002') {
        throw new BadRequestException('This passkey is already registered');
      }
      throw error;
    }
  }

  // Deliberately no allowCredentials - an empty/omitted list is what makes
  // this a usernameless ceremony (the browser's own account picker offers
  // every discoverable credential registered for this rpID, not just one
  // account's). userVerification: 'required' asks the authenticator to
  // prove a PIN/biometric, not just presence - see verifyAuthentication's
  // own comment on why a 'required' REQUEST here doesn't mean verification
  // fails outright if the RESPONSE still comes back without it.
  async generateAuthenticationOptionsFor(): Promise<{
    options: PublicKeyCredentialRequestOptionsJSON;
    challengeToken: string;
  }> {
    const { rpID } = rpConfig();
    const options = await generateAuthenticationOptions({
      rpID,
      userVerification: 'required',
    });

    const challengeToken = this.jwtService.sign(
      { purpose: PASSKEY_LOGIN_PURPOSE, challenge: options.challenge },
      { expiresIn: PASSKEY_CHALLENGE_TOKEN_TTL },
    );

    return { options, challengeToken };
  }

  // No expectedUserId to check against here (unlike verifyChallengeToken
  // above) - nobody's identity is known until verifyAuthentication resolves
  // the credentialId below.
  private verifyLoginChallengeToken(token: string): string {
    let payload: { purpose?: string; challenge?: string };
    try {
      payload = this.jwtService.verify(token);
    } catch {
      throw new UnauthorizedException('Passkey login challenge is invalid or has expired');
    }
    if (payload.purpose !== PASSKEY_LOGIN_PURPOSE || !payload.challenge) {
      throw new UnauthorizedException('Passkey login challenge is invalid or has expired');
    }
    return payload.challenge;
  }

  // Returns userId (never a full user - PasskeyController fetches that
  // itself, same "service returns primitives, controller assembles the
  // response" split as verifyAndSaveRegistration returning a summary
  // rather than a full DTO) and userVerified, which
  // PasskeyController.loginVerify uses to decide whether this login earns
  // the "already MFA-equivalent" bypass (Tahap 3 Sprint 2 decision) or
  // falls through to the same isMfaEnabled/trusted-device/challenge branch
  // password and OAuth login already run.
  async verifyAuthentication(
    response: AuthenticationResponseJSON,
    challengeToken: string,
  ): Promise<{ userId: string; userVerified: boolean }> {
    const expectedChallenge = this.verifyLoginChallengeToken(challengeToken);
    const { rpID, origin } = rpConfig();

    // Looking this up BY the assertion's own credential id (rather than
    // trying to resolve a user first) is what makes the ceremony
    // usernameless - see WebAuthnCredential's `id` in @simplewebauthn's own
    // docs. A generic 401 here (not "unknown passkey") avoids confirming or
    // denying that any particular credential exists.
    const passkey = await this.prisma.passkey.findUnique({
      where: { credentialId: response.id },
    });
    if (!passkey) {
      throw new UnauthorizedException('Could not verify passkey login');
    }

    let verification: Awaited<ReturnType<typeof verifyAuthenticationResponse>>;
    try {
      verification = await verifyAuthenticationResponse({
        response,
        expectedChallenge,
        expectedOrigin: origin,
        expectedRPID: rpID,
        credential: {
          id: passkey.credentialId,
          publicKey: passkey.publicKey,
          counter: Number(passkey.counter),
          transports: passkey.transports as AuthenticatorTransportFuture[],
        },
        // Same reasoning as verifyAndSaveRegistration's own override, one
        // step further: Sprint 2's own decision is that an assertion
        // WITHOUT real user verification must still be allowed to
        // authenticate (the credential is genuinely this user's), it just
        // doesn't earn the MFA-equivalence bypass - PasskeyController
        // reads authenticationInfo.userVerified below and falls back to
        // the normal MFA gate when false, rather than this call rejecting
        // the login outright.
        requireUserVerification: false,
      });
    } catch {
      throw new UnauthorizedException('Could not verify passkey login');
    }

    if (!verification.verified) {
      throw new UnauthorizedException('Could not verify passkey login');
    }

    // Clone-detection backstop: verifyAuthenticationResponse itself already
    // rejected a counter that failed to increase (excusing authenticators
    // that always report 0) before reaching here - persisting the new
    // value is what makes that check meaningful on the NEXT login.
    await this.prisma.passkey.update({
      where: { id: passkey.id },
      data: {
        counter: BigInt(verification.authenticationInfo.newCounter),
        lastUsedAt: new Date(),
      },
    });

    return { userId: passkey.userId, userVerified: verification.authenticationInfo.userVerified };
  }

  async list(userId: string): Promise<PasskeySummary[]> {
    const passkeys = await this.prisma.passkey.findMany({
      where: { userId },
      orderBy: { createdAt: 'asc' },
    });
    return passkeys.map(toSummary);
  }

  async rename(userId: string, id: string, name: string): Promise<PasskeySummary> {
    const trimmedName = name.trim();
    if (!trimmedName) {
      throw new BadRequestException('Name cannot be empty');
    }
    const { count } = await this.prisma.passkey.updateMany({
      where: { id, userId },
      data: { name: trimmedName },
    });
    if (count === 0) {
      throw new NotFoundException(`Passkey ${id} not found`);
    }
    const passkey = await this.prisma.passkey.findUniqueOrThrow({ where: { id } });
    return toSummary(passkey);
  }

  // Hard delete, same deleteMany-by-userId+id pattern as
  // AuthService.unlinkOAuthProvider (see Passkey model's own comment on why
  // this is a hard delete rather than TrustedDevice's soft revokedAt).
  // Tahap 3 Sprint 2 - now that passkey login exists, this needs the same
  // "at least one sign-in method must remain" guard as
  // AuthService.unlinkOAuthProvider, mirrored rather than shared (see this
  // file's header comment on why login methods return primitives, not
  // shared cross-service calls, for the same reasoning duplicating this
  // few-line check keeps the two services independent).
  async delete(userId: string, id: string): Promise<void> {
    const passkeyCount = await this.prisma.passkey.count({ where: { userId } });
    if (passkeyCount <= 1) {
      const user = await this.prisma.user.findUniqueOrThrow({
        where: { id: userId },
        select: { password: true },
      });
      const oauthCount = await this.prisma.oAuthIdentity.count({ where: { userId } });
      if (!user.password && oauthCount === 0) {
        throw new BadRequestException('At least one sign-in method must remain on your account');
      }
    }

    const { count } = await this.prisma.passkey.deleteMany({ where: { id, userId } });
    if (count === 0) {
      throw new NotFoundException(`Passkey ${id} not found`);
    }
  }
}
